name: pythiachem

channels:
  - conda-forge

dependencies:
  - python>=3.9.13
  - pip>=22.2.2
  - pip:
    - imbalanced-learn==0.9.1
    - matplotlib==3.3.2
    - matplotlib-inline==0.1.2
    - matplotlib-venn==0.11.7
    - mlxtend==0.20.0
    - mordred==1.2.0
    - numpy==1.23.3
    - pandas==1.4.4
    - py3dmol==1.8.1
    - rdkit==2022.09.1
    - scikit-learn==0.24.2
    - scikit-plot==0.3.7
    - scipy==1.9.2
    - seaborn==0.11.1
    - tqdm==4.64.1
