name: pythiachem

channels:
  - conda-forge

dependencies:
  - python>=3.11.5
  - pip>=20.0.2
  - pip:
    - imbalanced-learn==0.11.0
    - matplotlib==3.8.2
    - matplotlib-inline==0.1.6
    - matplotlib-venn==0.11.9
    - mlxtend==0.23.1
    - mordred==1.2.0
    - numpy==1.23.3
    - pandas==1.4.4
    - py3dmol==2.0.4
    - rdkit==2023.9.4
    - scikit-learn==1.4.0
    - scikit-plot==0.3.7
    - scipy==1.11.4
    - seaborn==0.13.1
    - tqdm==4.66.1
